version: '3.8'
services:
  gateway:
    build: ./gateway

    container_name:
      shareIt-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    env_file:
      - gateway.env

  server:
    build: ./server

    container_name:
      shareIt-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    env_file:
      - server.env

  db:
    image: postgres:14.4-alpine

    container_name:
      postgresql
    ports:
      - "5455:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - db.env